export const LIST_ALL = 'LIST_ALL'
export const ADD_TASK = 'ADD_TASK'
export const UPDATE_STATUS_TASK = 'UPDATE_STATUS_TASK'
export const DELETE_ITEM = 'DELETE_ITEM'
export const EDIT_TASK = 'EDIT_TASK'
export const FILTER_TABLE = 'FILTER_TABLE'